NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('news.urls')),
    path('accounts/', include('allauth.urls')),
]

news/urls.py
from django.urls import path
from .views import PostList, PostDetail, PostCreate, PostUpdate, PostDelete, RegisterView, upgrade_me

app_name = 'news'

urlpatterns = [
    path('', PostList.as_view(), name='posts'),
    path('post/<int:pk>/', PostDetail.as_view(), name='post_detail'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('update/<int:pk>', PostUpdate.as_view(), name='post_update'),
    path('delete/<int:pk>', PostDelete.as_view(), name='post_delete'),
    path('upgrade/', upgrade_me, name='upgrade')
]

news/models.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


class Author(models.Model):
    def __str__(self):
        return self.authorUser.username

    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:20] + '...'

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/posts/post/{self.id}'


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.commentUser.username

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label='Имя')
    last_name = forms.CharField(label='Фамилия')

    class Meta:
        model = User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2')

news/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Post
from django import forms

from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'categoryType', 'author']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter post title'
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'categoryType': forms.Select(attrs={
                'class': 'form-control',
            }),
            'author': forms.Select(attrs={
                'class': 'form-control',
            })
        }


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password')
    password2 = forms.CharField(max_length=16, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Confirm Password')

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

        def clean(self):
            username = self.cleaned_data.get('username')
            email = self.cleaned_data.get('email')
            if User.objects.filter(username=username).exists():
                raise forms.ValidationError("Пользователь с таким именем уже существует")
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError("Пользователь с таким email уже существует")
            return super().clean()


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", "password",)


class BasicSignupForm(SignupForm):

    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        basic_group = Group.objects.get_or_create(name='basic')[0]
        basic_group.user_set.add(user)
        return user

news/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, CreateView, UpdateView, DetailView, FormView, TemplateView
from django.contrib.auth.models import Group

from .models import Post
from .filters import PostFilter
from .forms import PostForm, RegisterForm, LoginForm


class PostList(ListView):
    model = Post
    template_name = 'news/posts.html'
    context_object_name = 'posts'
    ordering = ['-rating']
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        context['choices'] = Post.CATEGORY_CHOICES
        context['form'] = PostForm()
        context['is_not_author'] = not self.request.user.groups.filter(name='author').exists()
        return context

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
        return super().get(request, *args, **kwargs)


@login_required
def upgrade_me(request):
    user = request.user
    premium_group = Group.objects.get(name='author')
    if not request.user.groups.filter(name='author').exists():
        premium_group.user_set.add(user)
    return redirect('/posts/')


class PostDetail(DetailView):
    template_name = 'news/post.html'
    queryset = Post.objects.all()


class PostCreate(CreateView):
    template_name = 'news/post_create.html'
    form_class = PostForm


class PostUpdate(LoginRequiredMixin, UpdateView, PermissionRequiredMixin):
    template_name = 'news/post_create.html'
    form_class = PostForm
    permission_required = ('news.change _post',)

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class PostDelete(DeleteView):
    template_name = 'news/post_delete.html'
    queryset = Post.objects.all()
    success_url = reverse_lazy('news:posts')


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'news/register.html'
    success_url = '/'

    def form_valid(self, form):
        user = form.save()
        group = Group.objects.get(name='basic')
        user.groups.add(group)
        user.save()
        return super().form_valid(form)


class LoginView(FormView):
    model = User
    form_class = LoginForm
    template_name = 'news/login.html'
    success_url = '/posts/'

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


class LogoutView(LoginRequiredMixin, TemplateView):
    template_name = 'news/logout.html'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)

news/templates/news/login.html
{% extends "account/base.html" %}

{% block content %}

<h2>
 Войти в систему
</h2>

<form method="post" action="{% url 'news:login' %}" class="py-3">

 {% csrf_token %}

 <table>
   <tr>
     <td>{{ form.username.label_tag }}</td>
     <td>{{ form.username }}</td>
   </tr>
   <tr>
     <td>{{ form.password.label_tag }}</td>
     <td>{{ form.password }}</td>
   </tr>
 </table>

 <button type="submit" class="btn btn-primary">
   Вход
 </button>
</form>

<a class="btn btn-secondary" href="/posts/signup/"> Регистрация </a>

{% endblock content %}

news/templates/news/logout.html
{% extends "account/base.html" %}

{% block content %}
<h2> Вы вышли из системы </h2>
{% endblock %}

news/templates/news/post.html

{% extends 'layout/base.html' %}
{% load custom_filters %}

{% block title %}
    Post
{% endblock title %}
<!-- В контенте на странице мы выводим сам продукт, первичный ключ которого был передан в адрес -->
{% block content %}
    <h1>{{ post.title|censor_text }}</h1>
    <h4>{{ post.dateCreation|date:'d M Y' }}</h4>
    <hr>
    <p>{{ post.text|censor_text }}</p>
    <p>{{ post.author.authorUser }}</p>
{% endblock content %}

news/templates/news/post_create.html
{% extends 'layout/base.html' %}


{% block title %}
Post create
{% endblock title %}

{% block content %}

<h3>Post Information</h3>

<form method="POST">
 {% csrf_token %}
 {{ form }}
   <!-- Теперь нам нужна только готовая форма и кнопка -->
   <input class="btn btn-success" type="submit" value="Add">
</form>

{% endblock content %}

news/templates/news/post_delete.html
{% extends 'layout/base.html' %}

{% block title %}
Post delete
{% endblock title %}

{% block content %}

<h3>Delete this post?</h3>
<div class="card">
 <div class="card-header">
   <h3>
     {{ post.title }}
   </h3>
   <div>
     Text: <span class="badge bg-info">{{ post.text }}</span>
     Date: <span class="badge bg-info">{{ post.dateCreation|date:'d M Y' }}</span>
   </div>
 </div>
 <div class="card-body">
   {{ post.author.authorUser }}
 </div>
</div>
<form method="POST">
 {% csrf_token %}
   <input class="btn btn-success" type="submit" value="Delete">
</form>

{% endblock content %}

news/templates/news/posts.html
{% extends 'layout/base.html' %}
{% load custom_filters %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <h1>Все посты</h1>
    <h4>Количество постов {{ filter.qs|length }}</h4>
    <hr>
    {% if posts %}

        <form method="GET">
            {{ filter.form }}
            <input class="btn btn-primary" type="submit" value="Найти">
        </form>

        <table>
            <tr>
                <td>
                    Заголовок
                </td>
                <td>
                    Дата публикации
                </td>
                <td>
                    Текст
                </td>
                <td scope="col">
                    Действия
                </td>
            </tr>
        {% for post in filter.qs %}
            <tr>
                <td>
                    <a href="{% url 'news:post_detail' post.id %}">{{ post.title|censor_text }}</a>
                </td>
                <td>
                    {{ post.dateCreation|date:'d M Y' }}
                </td>
                <td>
                    {{ post.text|truncatechars:50|censor_text }}
                </td>
                <td>
                   <a href="{% url 'news:post_update' post.id %}">
                       Update
                   </a>
                   <a href="{% url 'news:post_delete' post.id %}">
                       Delete
                   </a>
                </td>
            </tr>
        {% endfor %}
        </table>

        {% include 'news/parts/paginator.html' %}

    {% else %}
        <h2>Постов нет</h2>
    {% endif %}

    <a style="display: block" class="btn btn-primary" href="logout/">Выйти</a>

    {% if is_not_author %}

        <a class="btn btn-info" href="{% url 'news:upgrade' %}">
         Хочу стать Автором!
        </a>
        {% else %}
        <h3>
         Вы Автор!
        </h3>
    {% endif %}

{% endblock content %}

news/templates/news/register.html
{% extends 'account/base.html' %}

{% block title %}
Register
{% endblock title %}

{% block content %}
<h2>
 Register
</h2>
<form method="post">
{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<input type="submit" value="Send">
</form>
{% endblock content %}